# listening address of transocks.
listen = "0.0.0.0:3128"    # default is "localhost:1081"

#proxy_url = "socks5://10.20.30.40:1080"  # for SOCKS5 server
proxy_url = "@PROXY_URL@"   # for HTTP proxy server

[log]
#filename = "./transocks.log"   # default to stderr
level = "warning"               # critical", error, warning, info, debug
format = "plain"              # plain, logfmt, json

